orario/course_calendar/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^search/$', 'course_calendar.views.search_courses', name='search-courses'),
)

orario/orario/urls.py
from django.conf.urls import patterns, include, url

import student
import scheduler
import course_calendar

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'orario.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('student.urls')),
    url(r'^', include('scheduler.urls')),
    url(r'^', include('course_calendar.urls')),
)

orario/course_calendar/models.py
import string
from django.db import models
from sortedm2m.fields import SortedManyToManyField
from scheduler.models import LectureSlot, TutorialSlot, LabSlot


class Course(models.Model):
    """
    Represents A Course, which is composed of one or many sections.
    """
    #: Course number, e.g. "SOEN 331."
    number = models.CharField(max_length=10)
    #: A short description of the course.
    title = models.CharField(max_length=255)
    #: The number of credits the course is worth.
    credits = models.DecimalField(max_digits=2, decimal_places=1)
    #: The prerequisite courses for this course.
    prereqs = models.ManyToManyField("self", symmetrical=False, related_name='prereq_by')
    #: The corequisite courses for this course.
    coreqs = models.ManyToManyField("self", symmetrical=False, related_name='coreq_by')

    def __unicode__(self):
        """Returns string representation of the course."""
        return "%s - %s" % (self.number, self.title)

    def is_coreq_for(self, course):
        """
        Returns whether this course is a corequisite for the specified
        course.
        """
        return self in course.coreqs.all()


class Section(models.Model):
    """
    Describes a course section that is a unique combination of a lecture,
    an optional tutorial, and an optional lab.
    """
    #: The course this section belongs to.
    course = models.ForeignKey(Course)
    #: The term the section belongs to.
    term = models.IntegerField()
    #: The lecture in this section.
    lecture = models.ForeignKey(LectureSlot)
    #: The tutorial in this section. Optional.
    tutorial = models.ForeignKey(TutorialSlot, null=True, blank=True)
    #: The lab in this section. Optional.
    lab = models.ForeignKey(LabSlot, null=True, blank=True)

    def __unicode__(self):
        """
        Returns the complete section code, e.g. AA AJ AL
        """
        return string.join([
            self.course.__unicode__(),
            self.code()])

    def code(self):
        return string.join([
            self.lecture.section_code,
            self.tutorial.section_code if self.tutorial is not None else '',
            self.lab.section_code if self.lab is not None else ''])

    def conflicts_with(self, other):
        """
        Returns true if the section has a time conflict with the specified
        Section or TimeSlot, and false otherwise.
        """
        from scheduler.models import TimeSlot
        assert isinstance(other, TimeSlot) or isinstance(other, Section)
        if isinstance(other, TimeSlot):
            return (
                other.conflicts_with(self.lecture) or
                other.conflicts_with(self.tutorial) or
                other.conflicts_with(self.lab)
            )
        elif isinstance(other, Section):
            lect_conflict = (
                other.lecture.conflicts_with(self.lecture) or
                other.lecture.conflicts_with(self.tutorial) or
                other.lecture.conflicts_with(self.lab)
            )
            if other.tutorial is not None:
                tut_conflict = (
                    other.tutorial.conflicts_with(self.lecture) or
                    other.tutorial.conflicts_with(self.tutorial) or
                    other.tutorial.conflicts_with(self.lab)
                )
            else:
                tut_conflict = False
            if other.lab is not None:
                lab_conflict = (
                    other.lab.conflicts_with(self.lecture) or
                    other.lab.conflicts_with(self.tutorial) or
                    other.lab.conflicts_with(self.lab)
                )
            else:
                lab_conflict = False
            return (
                lect_conflict or
                tut_conflict or
                lab_conflict
            )


class Program(models.Model):
    """
    A program can have one of many offered sequences.
    """
    #: Name of the program.
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

class Option(models.Model):
    """
    An option carries a course sequence.
    """
    #: Name of the option.
    name = models.CharField(max_length=255)
    #: Program that the Option belongs to.
    program = models.ForeignKey(Program)
    #: The courses listed in suggested order of completion.
    sequence = SortedManyToManyField(Course)

    def __unicode__(self):
        return "%s - %s" % (self.program.name, self.name)

    def get_next_courses(self, student):
        print repr(student.courses_taken.all())
        return self.sequence.exclude(pk__in=[course.pk for course in student.courses_taken.all()])

orario/course_calendar/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.db.models import Q

from models import Course


def search_courses(request):
    query = request.GET.get('query', None)
    if query:
        courses = Course.objects.filter(Q(number__icontains=query) | Q(title__icontains=query))
    else:
        courses = None
    print repr(courses)
    return render_to_response(
        'course_calendar/search.html',
        {'courses': courses, 'query': query},
        context_instance=RequestContext(request))

orario/templates/course_calendar/search.html
{% extends 'master.html' %}

{% block title %}Search Courses{% endblock %}

{% block subheader %}Search course listing{% endblock %}

{% block content %}
<div class="container">
  <form action="{% url 'search-courses' %}" method="get" class="form-inline">
    <div class="form-group">
      <label class="sr-only" for="query">Search terms</label>
      <input id="query" name="query" type="text" class="form-control" placeholder="e.g. COMP 248, system hardware, etc." {% if query %}value="{{ query }}"{% endif %}>
    </div>
    <button type="submit" class="btn btn-default">Search</button>
  </form>
  <hr>
  {% if courses %}
  {% for course in courses %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">{{ course }}</h3>
    </div>
    <div class="panel-body">
      <table class="table">
      {% for section in course.section_set.all %}
        <tr>
          <th colspan="3">Section {{ section.code }}</th>
        </tr>
        <tr>
          <td>Lecture {{ section.lecture.section_code }}</td>
          <td>{{ section.lecture.instructor }}</td>
          <td>{{ section.lecture.str_days }} {{ section.lecture.str_times }}</td>
        </tr>
        {% if section.tutorial %}
        <tr>
          <td>Tutorial {{ section.tutorial.section_code }}</td>
          <td>{{ section.tutorial.instructor }}</td>
          <td>{{ section.tutorial.str_days }} {{ section.tutorial.str_times }}</td>
        </tr>
        {% endif %}
        {% if section.lab %}
        <tr>
          <td>Lab {{ section.lab.section_code }}</td>
          <td>{{ section.lab.instructor }}</td>
          <td>{{ section.lab.str_days }} {{ section.lab.str_times }}</td>
        </tr>
        {% endif %}
      {% endfor %}
      </table>
    </div>
  </div>
  {% endfor %}
  {% endif %}
</div>
{% endblock %}